export const STOREFRONT_PRODUCT_LIST_REQUEST = 'STOREFRONT_PRODUCT_LIST_REQUEST';
export const STOREFRONT_PRODUCT_LIST_SUCCESS = 'STOREFRONT_PRODUCT_LIST_SUCCESS';
export const STOREFRONT_PRODUCT_LIST_FAIL = 'STOREFRONT_PRODUCT_LIST_FAIL';

export const STOREFRONT_PRODUCT_DETAILS_REQUEST = 'STOREFRONT_PRODUCT_DETAILS_REQUEST';
export const STOREFRONT_PRODUCT_DETAILS_SUCCESS = 'STOREFRONT_PRODUCT_DETAILS_SUCCESS';
export const STOREFRONT_PRODUCT_DETAILS_FAIL = 'STOREFRONT_PRODUCT_DETAILS_FAIL';

// Add these to your existing storefront/productConstants.ts file
export const STOREFRONT_SIMILAR_PRODUCTS_REQUEST = 'STOREFRONT_SIMILAR_PRODUCTS_REQUEST';
export const STOREFRONT_SIMILAR_PRODUCTS_SUCCESS = 'STOREFRONT_SIMILAR_PRODUCTS_SUCCESS';
export const STOREFRONT_SIMILAR_PRODUCTS_FAIL = 'STOREFRONT_SIMILAR_PRODUCTS_FAIL';
export const STOREFRONT_SIMILAR_PRODUCTS_RESET = 'STOREFRONT_SIMILAR_PRODUCTS_RESET';