export const STOREFRONT_PRODUCT_LIST_REQUEST = 'STOREFRONT_PRODUCT_LIST_REQUEST';
export const STOREFRONT_PRODUCT_LIST_SUCCESS = 'STOREFRONT_PRODUCT_LIST_SUCCESS';
export const STOREFRONT_PRODUCT_LIST_FAIL = 'STOREFRONT_PRODUCT_LIST_FAIL';