export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST';
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS';
export const REVIEW_CREATE_FAIL = 'REVIEW_CREATE_FAIL';
export const REVIEW_CREATE_RESET = 'REVIEW_CREATE_RESET';

export const REVIEW_UPDATE_REQUEST = 'REVIEW_UPDATE_REQUEST';
export const REVIEW_UPDATE_SUCCESS = 'REVIEW_UPDATE_SUCCESS';
export const REVIEW_UPDATE_FAIL = 'REVIEW_UPDATE_FAIL';
export const REVIEW_UPDATE_RESET = 'REVIEW_UPDATE_RESET';

export const REVIEW_VOTE_REQUEST = 'REVIEW_VOTE_REQUEST';
export const REVIEW_VOTE_SUCCESS = 'REVIEW_VOTE_SUCCESS';
export const REVIEW_VOTE_FAIL = 'REVIEW_VOTE_FAIL';
export const REVIEW_VOTE_RESET = 'REVIEW_VOTE_RESET';

export const REVIEW_REPORT_REQUEST = 'REVIEW_REPORT_REQUEST';
export const REVIEW_REPORT_SUCCESS = 'REVIEW_REPORT_SUCCESS';
export const REVIEW_REPORT_FAIL = 'REVIEW_REPORT_FAIL';
export const REVIEW_REPORT_RESET = 'REVIEW_REPORT_RESET';