export const DISCOUNT_OFFER_LIST_REQUEST = 'DISCOUNT_OFFER_LIST_REQUEST';
export const DISCOUNT_OFFER_LIST_SUCCESS = 'DISCOUNT_OFFER_LIST_SUCCESS';
export const DISCOUNT_OFFER_LIST_FAIL = 'DISCOUNT_OFFER_LIST_FAIL';

export const DISCOUNT_COUPON_LIST_REQUEST = 'DISCOUNT_COUPON_LIST_REQUEST';
export const DISCOUNT_COUPON_LIST_SUCCESS = 'DISCOUNT_COUPON_LIST_SUCCESS';
export const DISCOUNT_COUPON_LIST_FAIL = 'DISCOUNT_COUPON_LIST_FAIL';

export const DISCOUNT_OFFER_CREATE_REQUEST = 'DISCOUNT_OFFER_CREATE_REQUEST';
export const DISCOUNT_OFFER_CREATE_SUCCESS = 'DISCOUNT_OFFER_CREATE_SUCCESS';
export const DISCOUNT_OFFER_CREATE_FAIL = 'DISCOUNT_OFFER_CREATE_FAIL';
export const DISCOUNT_OFFER_CREATE_RESET = 'DISCOUNT_OFFER_CREATE_RESET';

export const DISCOUNT_COUPON_CREATE_REQUEST = 'DISCOUNT_COUPON_CREATE_REQUEST';
export const DISCOUNT_COUPON_CREATE_SUCCESS = 'DISCOUNT_COUPON_CREATE_SUCCESS';
export const DISCOUNT_COUPON_CREATE_FAIL = 'DISCOUNT_COUPON_CREATE_FAIL';
export const DISCOUNT_COUPON_CREATE_RESET = 'DISCOUNT_COUPON_CREATE_RESET';