export const INVENTORY_LIST_REQUEST = 'INVENTORY_LIST_REQUEST';
export const INVENTORY_LIST_SUCCESS = 'INVENTORY_LIST_SUCCESS';
export const INVENTORY_LIST_FAIL = 'INVENTORY_LIST_FAIL';

export const INVENTORY_UPDATE_REQUEST = 'INVENTORY_UPDATE_REQUEST';
export const INVENTORY_UPDATE_SUCCESS = 'INVENTORY_UPDATE_SUCCESS';
export const INVENTORY_UPDATE_FAIL = 'INVENTORY_UPDATE_FAIL';
export const INVENTORY_UPDATE_RESET = 'INVENTORY_UPDATE_RESET';