export const INVOICE_LIST_REQUEST = 'INVOICE_LIST_REQUEST';
export const INVOICE_LIST_SUCCESS = 'INVOICE_LIST_SUCCESS';
export const INVOICE_LIST_FAIL = 'INVOICE_LIST_FAIL';

export const INVOICE_DETAILS_REQUEST = 'INVOICE_DETAILS_REQUEST';
export const INVOICE_DETAILS_SUCCESS = 'INVOICE_DETAILS_SUCCESS';
export const INVOICE_DETAILS_FAIL = 'INVOICE_DETAILS_FAIL';
export const INVOICE_DETAILS_RESET = 'INVOICE_DETAILS_RESET';

export const ADMIN_INVOICE_BY_ORDER_REQUEST = 'ADMIN_INVOICE_BY_ORDER_REQUEST';
export const ADMIN_INVOICE_BY_ORDER_SUCCESS = 'ADMIN_INVOICE_BY_ORDER_SUCCESS';
export const ADMIN_INVOICE_BY_ORDER_FAIL = 'ADMIN_INVOICE_BY_ORDER_FAIL';
export const ADMIN_INVOICE_BY_ORDER_RESET = 'ADMIN_INVOICE_BY_ORDER_RESET';

export const INVOICE_DOWNLOAD_REQUEST = 'INVOICE_DOWNLOAD_REQUEST';
export const INVOICE_DOWNLOAD_SUCCESS = 'INVOICE_DOWNLOAD_SUCCESS';
export const INVOICE_DOWNLOAD_FAIL = 'INVOICE_DOWNLOAD_FAIL';
export const INVOICE_DOWNLOAD_RESET = 'INVOICE_DOWNLOAD_RESET';