export const MASTER_DATA_LIST_REQUEST = 'MASTER_DATA_LIST_REQUEST';
export const MASTER_DATA_LIST_SUCCESS = 'MASTER_DATA_LIST_SUCCESS';
export const MASTER_DATA_LIST_FAIL = 'MASTER_DATA_LIST_FAIL';

export const MASTER_DATA_CREATE_REQUEST = 'MASTER_DATA_CREATE_REQUEST';
export const MASTER_DATA_CREATE_SUCCESS = 'MASTER_DATA_CREATE_SUCCESS';
export const MASTER_DATA_CREATE_FAIL = 'MASTER_DATA_CREATE_FAIL';
export const MASTER_DATA_CREATE_RESET = 'MASTER_DATA_CREATE_RESET';

export const MASTER_DATA_DELETE_REQUEST = 'MASTER_DATA_DELETE_REQUEST';
export const MASTER_DATA_DELETE_SUCCESS = 'MASTER_DATA_DELETE_SUCCESS';
export const MASTER_DATA_DELETE_FAIL = 'MASTER_DATA_DELETE_FAIL';

export const MASTER_DATA_UPDATE_REQUEST = 'MASTER_DATA_UPDATE_REQUEST';
export const MASTER_DATA_UPDATE_SUCCESS = 'MASTER_DATA_UPDATE_SUCCESS';
export const MASTER_DATA_UPDATE_FAIL = 'MASTER_DATA_UPDATE_FAIL';
export const MASTER_DATA_UPDATE_RESET = 'MASTER_DATA_UPDATE_RESET';