export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST';
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS';
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL';
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';

// Add these below your existing admin order constants (like ORDER_DELIVER)
export const ORDER_CREATE_MANUAL_REQUEST = 'ORDER_CREATE_MANUAL_REQUEST';
export const ORDER_CREATE_MANUAL_SUCCESS = 'ORDER_CREATE_MANUAL_SUCCESS';
export const ORDER_CREATE_MANUAL_FAIL = 'ORDER_CREATE_MANUAL_FAIL';
export const ORDER_CREATE_MANUAL_RESET = 'ORDER_CREATE_MANUAL_RESET';

// Add these below your existing order constants
export const ORDER_PAY_MANUAL_REQUEST = 'ORDER_PAY_MANUAL_REQUEST';
export const ORDER_PAY_MANUAL_SUCCESS = 'ORDER_PAY_MANUAL_SUCCESS';
export const ORDER_PAY_MANUAL_FAIL = 'ORDER_PAY_MANUAL_FAIL';
export const ORDER_PAY_MANUAL_RESET = 'ORDER_PAY_MANUAL_RESET';