export const PURCHASE_CREATE_REQUEST = 'PURCHASE_CREATE_REQUEST';
export const PURCHASE_CREATE_SUCCESS = 'PURCHASE_CREATE_SUCCESS';
export const PURCHASE_CREATE_FAIL = 'PURCHASE_CREATE_FAIL';
export const PURCHASE_CREATE_RESET = 'PURCHASE_CREATE_RESET';

export const PURCHASE_DETAILS_REQUEST = 'PURCHASE_DETAILS_REQUEST';
export const PURCHASE_DETAILS_SUCCESS = 'PURCHASE_DETAILS_SUCCESS';
export const PURCHASE_DETAILS_FAIL = 'PURCHASE_DETAILS_FAIL';
export const PURCHASE_DETAILS_RESET = 'PURCHASE_DETAILS_RESET';

export const PURCHASE_CONFIRM_REQUEST = 'PURCHASE_CONFIRM_REQUEST';
export const PURCHASE_CONFIRM_SUCCESS = 'PURCHASE_CONFIRM_SUCCESS';
export const PURCHASE_CONFIRM_FAIL = 'PURCHASE_CONFIRM_FAIL';
export const PURCHASE_CONFIRM_RESET = 'PURCHASE_CONFIRM_RESET';

export const PURCHASE_BILL_REQUEST = 'PURCHASE_BILL_REQUEST';
export const PURCHASE_BILL_SUCCESS = 'PURCHASE_BILL_SUCCESS';
export const PURCHASE_BILL_FAIL = 'PURCHASE_BILL_FAIL';
export const PURCHASE_BILL_RESET = 'PURCHASE_BILL_RESET';

export const PURCHASE_LIST_REQUEST = 'PURCHASE_LIST_REQUEST';
export const PURCHASE_LIST_SUCCESS = 'PURCHASE_LIST_SUCCESS';
export const PURCHASE_LIST_FAIL = 'PURCHASE_LIST_FAIL';