export const PURCHASE_CREATE_REQUEST = 'PURCHASE_CREATE_REQUEST';
export const PURCHASE_CREATE_SUCCESS = 'PURCHASE_CREATE_SUCCESS';
export const PURCHASE_CREATE_FAIL = 'PURCHASE_CREATE_FAIL';
export const PURCHASE_CREATE_RESET = 'PURCHASE_CREATE_RESET';

export const PURCHASE_DETAILS_REQUEST = 'PURCHASE_DETAILS_REQUEST';
export const PURCHASE_DETAILS_SUCCESS = 'PURCHASE_DETAILS_SUCCESS';
export const PURCHASE_DETAILS_FAIL = 'PURCHASE_DETAILS_FAIL';
export const PURCHASE_DETAILS_RESET = 'PURCHASE_DETAILS_RESET';

export const PURCHASE_LIST_REQUEST = 'PURCHASE_LIST_REQUEST';
export const PURCHASE_LIST_SUCCESS = 'PURCHASE_LIST_SUCCESS';
export const PURCHASE_LIST_FAIL = 'PURCHASE_LIST_FAIL';

export const PURCHASE_RECEIVE_REQUEST = 'PURCHASE_RECEIVE_REQUEST';
export const PURCHASE_RECEIVE_SUCCESS = 'PURCHASE_RECEIVE_SUCCESS';
export const PURCHASE_RECEIVE_FAIL = 'PURCHASE_RECEIVE_FAIL';
export const PURCHASE_RECEIVE_RESET = 'PURCHASE_RECEIVE_RESET';

export const PURCHASE_DOWNLOAD_REQUEST = 'PURCHASE_DOWNLOAD_REQUEST';