export const REPORT_SALES_PRODUCTS_REQUEST = 'REPORT_SALES_PRODUCTS_REQUEST';
export const REPORT_SALES_PRODUCTS_SUCCESS = 'REPORT_SALES_PRODUCTS_SUCCESS';
export const REPORT_SALES_PRODUCTS_FAIL = 'REPORT_SALES_PRODUCTS_FAIL';

export const REPORT_PURCHASES_PRODUCTS_REQUEST = 'REPORT_PURCHASES_PRODUCTS_REQUEST';
export const REPORT_PURCHASES_PRODUCTS_SUCCESS = 'REPORT_PURCHASES_PRODUCTS_SUCCESS';
export const REPORT_PURCHASES_PRODUCTS_FAIL = 'REPORT_PURCHASES_PRODUCTS_FAIL';

export const REPORT_SALES_CUSTOMERS_REQUEST = 'REPORT_SALES_CUSTOMERS_REQUEST';
export const REPORT_SALES_CUSTOMERS_SUCCESS = 'REPORT_SALES_CUSTOMERS_SUCCESS';
export const REPORT_SALES_CUSTOMERS_FAIL = 'REPORT_SALES_CUSTOMERS_FAIL';

export const REPORT_PURCHASES_VENDORS_REQUEST = 'REPORT_PURCHASES_VENDORS_REQUEST';
export const REPORT_PURCHASES_VENDORS_SUCCESS = 'REPORT_PURCHASES_VENDORS_SUCCESS';
export const REPORT_PURCHASES_VENDORS_FAIL = 'REPORT_PURCHASES_VENDORS_FAIL';