export const SETTINGS_DETAILS_REQUEST = 'SETTINGS_DETAILS_REQUEST';
export const SETTINGS_DETAILS_SUCCESS = 'SETTINGS_DETAILS_SUCCESS';
export const SETTINGS_DETAILS_FAIL = 'SETTINGS_DETAILS_FAIL';

export const SETTINGS_UPDATE_REQUEST = 'SETTINGS_UPDATE_REQUEST';
export const SETTINGS_UPDATE_SUCCESS = 'SETTINGS_UPDATE_SUCCESS';
export const SETTINGS_UPDATE_FAIL = 'SETTINGS_UPDATE_FAIL';
export const SETTINGS_UPDATE_RESET = 'SETTINGS_UPDATE_RESET';