export const USER_INVOICE_BY_ORDER_REQUEST = 'USER_INVOICE_BY_ORDER_REQUEST';
export const USER_INVOICE_BY_ORDER_SUCCESS = 'USER_INVOICE_BY_ORDER_SUCCESS';
export const USER_INVOICE_BY_ORDER_FAIL = 'USER_INVOICE_BY_ORDER_FAIL';
export const USER_INVOICE_BY_ORDER_RESET = 'USER_INVOICE_BY_ORDER_RESET';

export const USER_INVOICE_DETAILS_REQUEST = 'USER_INVOICE_DETAILS_REQUEST';
export const USER_INVOICE_DETAILS_SUCCESS = 'USER_INVOICE_DETAILS_SUCCESS';
export const USER_INVOICE_DETAILS_FAIL = 'USER_INVOICE_DETAILS_FAIL';
export const USER_INVOICE_DETAILS_RESET = 'USER_INVOICE_DETAILS_RESET';

export const USER_INVOICE_LIST_REQUEST = 'USER_INVOICE_LIST_REQUEST';
export const USER_INVOICE_LIST_SUCCESS = 'USER_INVOICE_LIST_SUCCESS';
export const USER_INVOICE_LIST_FAIL = 'USER_INVOICE_LIST_FAIL';
export const USER_INVOICE_LIST_RESET = 'USER_INVOICE_LIST_RESET';

export const USER_INVOICE_DOWNLOAD_REQUEST = 'USER_INVOICE_DOWNLOAD_REQUEST';
export const USER_INVOICE_DOWNLOAD_SUCCESS = 'USER_INVOICE_DOWNLOAD_SUCCESS';
export const USER_INVOICE_DOWNLOAD_FAIL = 'USER_INVOICE_DOWNLOAD_FAIL';
export const USER_INVOICE_DOWNLOAD_RESET = 'USER_INVOICE_DOWNLOAD_RESET';