export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST';
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS';
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL';
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET';

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const USER_ORDER_DETAILS_REQUEST = 'USER_ORDER_DETAILS_REQUEST';
export const USER_ORDER_DETAILS_SUCCESS = 'USER_ORDER_DETAILS_SUCCESS';
export const USER_ORDER_DETAILS_FAIL = 'USER_ORDER_DETAILS_FAIL';

export const ORDER_VERIFY_REQUEST = 'ORDER_VERIFY_REQUEST';
export const ORDER_VERIFY_SUCCESS = 'ORDER_VERIFY_SUCCESS';
export const ORDER_VERIFY_FAIL = 'ORDER_VERIFY_FAIL';

export const STRIPE_INTENT_REQUEST = 'STRIPE_INTENT_REQUEST';
export const STRIPE_INTENT_SUCCESS = 'STRIPE_INTENT_SUCCESS';
export const STRIPE_INTENT_FAIL = 'STRIPE_INTENT_FAIL';
export const STRIPE_INTENT_RESET = 'STRIPE_INTENT_RESET';