export const textSchema = {
    en: {
      auth: {
        loginTitle: 'Welcome Back',
        registerTitle: 'Create an Account',
        emailLabel: 'Email Address',
        passwordLabel: 'Password',
        nameLabel: 'Full Name',
        mobileLabel: 'Mobile Number',
        cityLabel: 'City',
        stateLabel: 'State',
        pincodeLabel: 'Pincode',
        loginBtn: 'Sign In',
        registerBtn: 'Sign Up',
        noAccount: "Don't have an account?",
        hasAccount: 'Already have an account?',
      },
      common: {
        brandName: 'MDesk',
        home: 'Home',
        cart: 'Cart',
        orders: 'Orders',
        dashboard: 'Dashboard',
        products: 'Products',
        categories: 'Categories',
        inventory: 'Inventory',
        masterData: 'Master Data',
        coupons: "Coupons",
        login: 'Login',
        logout: 'Logout',
        footerRights: '© 2026 MDesk E-commerce. All rights reserved.',
      },
      adminAuth: {
        loginTitle: 'Admin Portal Login',
        registerTitle: 'Admin Portal Registration',
        adminSecretLabel: 'Admin Secret Key (Optional)',
      },
      adminProducts: {
        title: 'Product Management',
        addProductBtn: 'Add New Product',
        editBtn: 'Edit',
        deleteBtn: 'Delete',
        formTitleAdd: 'Create New Product',
        formTitleEdit: 'Edit Product',
        nameLabel: 'Product Name',
        categoryLabel: 'Category',
        typeLabel: 'Type',
        materialLabel: 'Material',
        colorsLabel: 'Colors (comma separated)',
        salesPriceLabel: 'Sales Price',
        salesTaxLabel: 'Sales Tax (%)',
        purchasePriceLabel: 'Purchase Price',
        purchaseTaxLabel: 'Purchase Tax (%)',
        publishedLabel: 'Published on Storefront',
        saveBtn: 'Save Product',
        cancelBtn: 'Cancel',
        tableHeaders: {
          name: 'Name',
          category: 'Category',
          price: 'Sales Price',
          stock: 'Current Stock',
          status: 'Status',
          actions: 'Actions',
        }
      },
      adminCategories: {
        title: 'Category Management',
        addCategoryBtn: 'Add New Category',
        editBtn: 'Edit',
        deleteBtn: 'Delete',
        formTitleAdd: 'Create New Category',
        formTitleEdit: 'Edit Category',
        nameLabel: 'Category Name',
        descLabel: 'Description',
        activeLabel: 'Is Active',
        saveBtn: 'Save Category',
        cancelBtn: 'Cancel',
        tableHeaders: {
          name: 'Name',
          description: 'Description',
          status: 'Status',
          actions: 'Actions',
        }
      },
    },
  };